config/routes.rb
CvHackathon::Application.routes.draw do
  devise_for :users

  resources :linked_in_profiles
  
  resources :contact_infos do
    member do
      post 'update'
    end
  end

  resources :resumes do
    member do
      get 'copy'
      post 'update'
    end
  end

  resources :sections do
    member do
      post 'update'
    end
  end

  resources :parts do
    member do
      post 'update'
    end
  end

  root :to => 'main#index'

end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :user
  has_many :sections, :dependent => :destroy

  attr_accessible :name
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_filter :authenticate_user!

  # GET /resumes
  # GET /resumes.json
  def index
    @contact_info = current_user.contact_info
    @resumes = Resume.all( :conditions => { :user_id => current_user.id }, :include => { :sections => :parts } )
    #puts YAML::dump(@jsonresumes)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @resumes.as_json(
        :include => { :sections => { :include => :parts } } ) }
    end
  end



  # GET /resumes/1
  # GET /resumes/1.json
  def show
    @resume = Resume.find(params[:id])

    respond_to do |format|
      format.html { redirect_to :action => :index }
      format.json { render json: {
        resume: @resume.as_json( :include => { :sections => { :include => :parts } } ),
        contact_info: current_user.contact_info
      } }
    end
  end


  # GET /resumes/new
  # GET /resumes/new.json
  def new
    @resume = Resume.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @resume }
    end
  end

  # GET /resumes/1/edit
  def edit
    @resume = Resume.find(params[:id])
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = current_user.resumes.new(params[:resume])

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render json: @resume, status: :created, location: @resume }
      else
        format.html { render action: "new" }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /resumes/1
  # PUT /resumes/1.json
  def update
    if params[:pk]
      @resume = Resume.find(params[:pk])
      @resume.update_attributes( params[:name] => params[:value] )
      
      if @resume.save
        render json: { :results => true }
      else
        render json: { :results => false }
      end
    else
      @resume = Resume.find(params[:id])

      respond_to do |format|
        if @resume.update_attributes(params[:resume])
          format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @resume.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy

    render nothing: true
  end

  def copy
    @resume = Resume.find(params[:id]).dup( :include => { :sections => :parts } )
    @resume.name = "#{@resume.name} (copy)"
    @resume.save

    redirect_to resumes_url
  end
end

app/views/resumes/_form.html.erb
<%= form_for(@resume) do |f| %>
  <% if @resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing resume</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
 <div id="main_content">
      <div class="container">

        <div class="span12 main-page">          
          
          <div class="span8 resume-details">
            <div class="accordion" id="accordion1">

              <div class="personal-info">
                <div class="field"><a href="#" class="editable section first-name" data-type="text" data-pk="<%= @contact_info.id %>" data-name="first_name" data-url="/contact_infos/<%= @contact_info.id %>"><%= @contact_info.first_name %></a></div>

                <div class="field"><a href="#" class="editable section last-name" data-type="text" data-pk="<%= @contact_info.id %>" data-name="last_name" data-url="/contact_infos/<%= @contact_info.id %>"><%= @contact_info.last_name %></a></div>

                <div class="field"><a href="#" class="editable section email" data-type="text" data-pk="<%= @contact_info.id %>" data-name="email" data-url="/contact_infos/<%= @contact_info.id %>"><%= @contact_info.email %></a></div>
                
              </div>
              
              <div class="accordion-group section-area" id="resumes-list">
              </div>

            </div>
          </div>

          <!-- <ul id="resumes-list">
          </ul> -->

          <script id="resume-template" type="text/x-handlebars-template">
            <li class="resume-{{ id }} resume">
              <h1>
                <a href="#" class="editable section" data-type="text" data-pk="{{ id }}" data-name="name" data-url="/resumes/{{ id }}">{{ name }}</a>
              </h1>
              <!--<a href="/resumes/{{ id }}/copy" class="btn btn-primary">Duplicate</a>-->
              <ul id="sections-list-{{ id }}">
              </ul>
              <a class="create-section-area" href="#" id="section-create-{{ id }}" data-type="text" data-pk="{{ id }}">Create Section</a> 
            </li>
          </script>


          <script id="section-template" type="text/x-handlebars-template">
            <li id="section-{{ id }}" class="section">
            

              <div class="accordion-heading section-header">
                <a data-toggle="collapse" data-parent="#accordion1" href="#collapse-{{ id }}" class=" accordion-toggle" data-type="text" data-pk="{{ id }}" data-name="name" data-url="/sections/{{ id }}">{{ name }}</a>
              </div>


              <div id="collapse-{{ id }}" class="accordion-body collapse out ">
                <div class="section-functionality">
                  <h4><a href="#" class="editable accordion-toggle" data-type="text" data-pk="{{ id }}" data-name="name" data-url="/sections/{{ id }}">{{ name }}</a></h4>

                  <a href="#" class="pull-right last" title="">
                    <span class="livicon delete-section" data="{{ id }}" data-n="trash" data-s="32" data-c="#E74C3C" data-hc="#C0392B"data-et="click"></span>
                  </a>

                  <!-- <a href="#" class="pull-right" title="">
                    <span class="livicon" data-n="edit" data-s="32" data-c="#F1C40F" data-hc="#F39C12" data-et="click"></span>
                  </a> -->

                  <a href="#"  class="pull-right" title="">
                    <span id="part-create-{{ id }}" data-type="text" data-pk="{{ id }}" class="livicon" data-n="plus" data-s="32" data-c="#2ECC71" data-hc="#27AE60" data-et="click"></span>
                  </a>

                </div>
                <div class="accordion-inner section-info-container">
                  <div class="accordion" id="parts-list-{{ id }}">
                 </div>
                </div>
              </div>

              
              <ul id="parts-list-{{ id }}">
              </ul>
              <!-- <a href="#" id="part-create-{{ id }}" data-type="text" data-pk="{{ id }}">Create Par</a>-->

            </li>
          </script>

          <script id="part-template" type="text/x-handlebars-template">
            
              <div class="section-info">
                <div class="accordion-group info-area">

                  <div class="accordion-heading info-header">
                    
                      <a href="#collapse-part-{{ id }}" data-toggle="collapse"  data-parent="#parts-list-{{ section_id }}" class="accordion-toggle" data-type="text" data-pk="{{ id }}" data-name="name" data-url="/parts/{{ id }}">{{ name }}</a>
                  </div>

                  <div id="collapse-part-{{ id }}" class="accordion-body collapse out info">
                    <div class="info-functionality">
                      <h4><span class="editable data" data-type="text" data-pk="{{ id }}" data-name="name" data-url="/parts/{{ id }}">{{ name }}</span></h4>

                      <a href="" class="pull-right last" title="">
                        <span class="livicon delete-part" data="{{ id }}" data-n="trash" data-s="32" data-c="#E74C3C" data-hc="#C0392B" data-et="click"></span>
                      </a>

                    </div> <!-- end info-functionality -->

                    <div class="accordion-inner info-inner">
                      <ul>
                        <li><span class="field">Location: </span><span class="editable data" data-type="text" data-pk="{{ id }}" data-name="location" data-url="/parts/{{ id }}">{{ location }}</span></li>
                        <li><span class="field">Start Date: </span><span class="editable data" data-type="text" data-pk="{{ id }}" data-name="start_date" data-url="/parts/{{ id }}">{{start_date}}</span></li>
                        <li><span class="field">End Date: </span><span class="editable data" data-type="text" data-pk="{{ id }}" data-name="end_date" data-url="/parts/{{ id }}">{{ end_date }}</span></li>
                        <li><span class="field">Description: </span><span class="editable data" data-type="text" data-pk="{{ id }}" data-name="notes" data-url="/parts/{{ id }}">{{ notes }}</span></li>
                      </ul>
                    </div>

                  </div> <!-- end .info -->

                </div> <!-- end info-area -->
              </div> <!-- end .section-info -->

            <!--<li id="part-{{ id }}" class="part">
              <h5>
                <a href="#" class="editable" data-type="text" data-pk="{{ id }}" data-name="name" data-url="/parts/{{ id }}">{{ name }}</a>
                <button class="btn btn-danger delete-part" data="{{ id }}">Delete</button>
              </h5>
              <p>
                <a href="#" class="editable" data-type="text" data-pk="{{ id }}" data-name="location" data-url="/parts/{{ id }}">{{ location }}</a>
              </p>
              <p>
                <a href="#" class="editable" data-type="text" data-pk="{{ id }}" data-name="start_date" data-url="/parts/{{ id }}">{{ start_date }}</a> -
                <a href="#" class="editable" data-type="text" data-pk="{{ id }}" data-name="end_date" data-url="/parts/{{ id }}">{{ end_date }}</a>
              </p>
              <p>
                <a href="#" class="editable" data-type="text" data-pk="{{ id }}" data-name="notes" data-url="/parts/{{ id }}">{{ notes }}</a>
              </p>
            </li>-->

          </script>

          <br />

          <%= link_to 'Import from LinkedIn', linked_in_profiles_path, class: "btn btn-inverse pull-right linkedin" %>

          <div class="span4 resumes">

            <div class="box pinned">
              <div class="upper">
                <h3>Resumes</h3>

                <a href="<%= new_resume_path %>" class="add-RESUME pull-right" title="">
                  <span class="livicon ui-button" data-n="plus" data-s="32" data-c="#2ECC71" data-hc="#27AE60" data-a="1" data-l="0" data-i="3" data-d="0" data-et="hover" data-op="0"></span>
                </a>
              </div> <!-- end .upper -->

              <div class="versions">
                <ul>
                  <% @resumes.each do |resume| %>
                    <li class="resume-<%= resume.id %>">
                      <a href="#" class="resume-link" data="<%= resume.id %>" title=""><%= resume.name %></a>

                      <a href="#" class="delete-resume pull-right" data="<%= resume.id %>" title="">
                        <span class="livicon ui-button" data-n="minus" data-s="28" data-c="#E74C3C" data-hc="#C0392B" data-et="hover"></span>
                      </a>

                      <!-- Previous code
                      <a href="/resumes/{{ id }}/copy" class="btn btn-primary">Duplicate</a>
                      -->
                      <a href="/resumes/<%= resume.id %>/copy" class="pull-right dup" title="">
                        <span class="livicon ui-button" data-n="recycled" data-s="28" data-c="#E67E22" data-hc="#D35400" data-et="hover"></span>
                      </a>
                    </li>
                  <% end %>
                </ul>
              </div>

              <div class="export">
                <a id="export_btn" href="#" title="" class="btn btn-large btn-block btn-danger">

                  <i class="livicon ui-button" data-n="external-link" data-s="18" data-c="#FFF" data-et="hover"></i>

                  <span>Export CV to PDF</span>

                </a>
              </div>
            </div>
            
          </div>

        </div>

      </div> <!-- /container -->
    </div> <!-- /main_content -->

app/views/resumes/new.html.erb
<div id="main_content">
 	<div class="container">

      	<h1>New resume</h1>

		<%= render 'form' %>

		<%= link_to 'Back', resumes_path %>
		
	</div>
</div>

app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <%= @resume.name %>
  <% @resume.sections.each do |section| %>
    <h2><%= section.name %></h2>
    <% section.parts.each do |part| %>
      <h3><%= part.name %></h3>
      <p><%= part.details[:location] %></p>
    <% end %>
  <% end %>
</div>

<%= form_for(@section) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script id="entry-template" type="text/x-handlebars-template">
<div class="entry">
<h1>{{title}}</h1>
  <div class="body">
    {{body}}
  </div>
</div>
</script>

<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>